### ISSUE TITLE
Justify images and multiple gliders on one page

### ISSUE THREAD

**Issue by turc0209** [turc0209/portfolio#2]
Hi @abhaysharma ! 
I ran into a few roadblocks. First, the social media links on my home page won't justify to the center of their flex items no matter what I do.
<img width="1331" alt="Screenshot 2023-12-08 at 12 05 14 PM" src="https://github.com/turc0209/portfolio/assets/133021335/3f724181-62e0-4537-986b-d1a4e4cbf74d">
Second, I can't seem to get more than one glider to load on the "My Work" page. I think I'd need JS knowledge to get that to work (what I messed with didn't do anything):
<img width="414" alt="Screenshot 2023-12-08 at 12 06 59 PM" src="https://github.com/turc0209/portfolio/assets/133021335/ece8586e-cbe4-4b91-b281-e3f0883a1378">

Thank you so much!

**Comment by abhaysharma** [comment]
@turc0209 here are the solutions to try:
Social Media Icons
- add a class of `justify-content-center` to the `row`
- change the class of `col` to the class of `col-auto` for the three icons, this will make the columns only take the width needed for their content.

Glider
- I am assuming you wan to display more than one sliders.
- from the demo page you will  need to copy the corresponding JS for the glider that you want to build.
- Example if you want to show 3 images at a time this is the code
```
new Glider(document.querySelector('.glider'), {
  slidesToShow: 3,
  dots: '#dots',
  arrows: {
    prev: '.glider-prev',
    next: '.glider-next'
  }
});
```

Now you will replace your code from the `line 154-162` with the above on your home page.

**Comment by turc0209** [comment]
The social media icons work now, thank you!
For the glider, the single slide to show was the way I wanted it to look, I mean that I want 3 carousels on one page. Is that possible with glider.js? I can't find information on multiple gliders on their site, just how to make one glider. Thank you!
<img width="583" alt="Screenshot 2023-12-08 at 6 52 16 PM" src="https://github.com/turc0209/portfolio/assets/133021335/304fd797-1cb7-43e9-a87e-560d5144aeb7">

**Comment by abhaysharma** [comment]
@turc0209 now I understand better. Yes, it is possible with some modifications:
1. the main glider class will be different
2. next and previous buttons will have additional classes
3. dots will have different id

Here is the HTML code
```
<div class="glider-contain w-75 pt-4 pb-4">
      <div class="glider2">
        <div>
          <img class="w-100 rounded-3" src="images/character-design-4.jpg" alt="Character Design 4">
        </div>
        <div>
          <img class="w-75 rounded-3" src="images/painting-1.JPG" alt="Painting of Fish">
        </div>
        <div>
          <img class="w-100 rounded-3" src="images/character-design-3.jpg" alt="Character Design 3">
        </div>
        <div>
          <img class="w-100 rounded-3" src="images/005_SHINING_RAIKOU.jpg" alt="Character Design 1">
        </div>
      </div>

      <button aria-label="Previous" class="glider-prev prev2">«</button>
      <button aria-label="Next" class="glider-next next2">»</button>
      <div role="tablist" class="dots" id="points"></div>
    </div> <!--closes glider-->
```

Based on the HTML classes and ids, you will need to add a new JS initiator for these new gliders in the same script tag.
```
new Glider(document.querySelector('.glider2'), {
      slidesToShow: 1,
      dots: '#points',
      draggable: true,
      arrows: {
        prev: '.prev2',
        next: '.next2'
      }
    });
```

**Comment by turc0209** [comment]
Works great, thank you very much!
